services:
  postgres:
    image: postgres:14
    container_name: gofiber_postgres
    environment:
      - POSTGRES_USER=${DB_USER:-cozy}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-gofiber}
    # - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    logging:
      driver: none
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - 'gofiber-net'

networks:
  gofiber-net:
    name: gofiber-net
