services:
  app:
    container_name: gofiber_app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd src && go mod download && air"
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    working_dir: /opt/gofiber-app
    volumes:
      - .:/opt/gofiber-app/:cached
    depends_on:
      - postgres
    networks:
      - 'gofiber-net'

  postgres:
    image: postgres:14
    container_name: gofiber_postgres
    environment:
      - POSTGRES_USER=${DB_USER:-cozy}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-gofiber}
    # - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    logging:
      driver: none
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - 'gofiber-net'

  pgadmin:
    image: dpage/pgadmin4
    container_name: gofiber_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-live@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    depends_on:
      - postgres
    ports:
      - '8888:80'
    restart: unless-stopped
    networks:
      - 'gofiber-net'
    

networks:
  gofiber-net:
    name: gofiber-net
