export '../../admin_app/screens/desktop/login_desktop_screen.dart';
//export './desktop/register_email_validation.dart';
export './desktop/register_email_validation_import.dart';
export './mobile/forget_mobile_screen.dart';
export './mobile/login_mobile_screen.dart';
export './mobile/profile_mobile.screen.dart';
export './mobile/register_mobile_screen.dart';
export './tablet/login_tablet_screen.dart';
export './mobile/splash_mobile_screen.dart';
