name: clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.1
  local_auth: ^2.1.7
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  assets:
    - .env
