name: barassage_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  android_intent_plus: ^5.0.2
  animate_gradient: ^0.0.3
  avatar_glow: ^3.0.1
  bloc: ^8.1.4
  build_verify: ^3.1.0
  calendar_date_picker2: ^1.1.5
  change_app_package_name: ^1.2.0
  chatview: ^2.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  dio: ^5.3.3
  equatable: ^2.0.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  ez_validator: ^0.3.5
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.3
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.5.0
  flutter_animated_button: ^2.0.3
  flutter_bloc: ^8.1.5
  flutter_chat_ui: ^1.6.14
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.0
  flutter_slidable_panel: ^1.1.3
  flutter_spinner_time_picker: ^0.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_stripe: ^10.2.0
  flutter_svg: ^2.0.0+1
  flutter_swipe_action_cell: ^3.1.3
  geolocator: ^12.0.0
  get_it: ^7.7.0
  glassmorphism: ^3.0.0
  go_router: ^14.1.4
  google_maps_flutter: ^2.7.0
  google_maps_place_picker_mb:
    git:
      url: https://github.com/alexdieudonne/google_maps_place_picker_mb.git
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  insta_assets_picker: ^2.3.0
  intl: any
  intl_phone_number_input: ^0.7.4
  ionicons: ^0.2.2
  jiffy: ^6.3.1
  latlong2: ^0.9.1
  loading_animation_widget: ^1.2.1
  local_auth: ^2.1.7
  logger: ^2.3.0
  lottie: ^3.1.2
  map_location_picker: ^1.3.0
  place_picker:
    git:
      url: https://github.com/alexdieudonne/locationpicker.git
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  pushable_button: ^0.0.4
  qr_flutter: ^4.0.0
  rename: ^3.0.2
  shared_preferences: ^2.2.2
  skeletonizer: ^1.3.0
  speech_to_text: ^6.6.0
  super_cupertino_navigation_bar: ^2.1.2
  url_launcher: ^6.2.6
  zod_validation: ^1.0.5
fonts:
  - family: Okta
    fonts:
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Black-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Bold-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-ExtraLight-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Heavy-Italic
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Medium-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Normal-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-SemiBold-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Thin-Italic.otf
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-UltraLight-Italic.otf
        style: italic

      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Black.otf
        style: 900
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Bold.otf
        weight: 700
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-ExtraLight.otf
        weight: 200
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Heavy.otf
        weight: 900
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Medium.otf
        weight: 500
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Normal.otf
        weight: 400
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-SemiBold.otf
        weight: 600
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-Thin.otf
        weight: 100
      - asset: assets/fonts/Groteskly-Yours-Okta-Neue-UltraLight.otf
        weight: 200

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter
  mockito: ^5.4.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/ill_dx.svg
    - assets/images/ill_register.svg
    - assets/svg/confirmed.svg
    - assets/svg/gift_ico.svg
    - assets/svg/gift.svg
    - assets/svg/test_gift.svg
    - assets/lotties/success_animation.json
    - assets/images/app-logo.png
