---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivoirejobs-api
  labels:
    app: ivoirejobs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivoirejobs-api
  template:
    metadata:
      labels:
        app: ivoirejobs-api
    spec:
      containers:
        - name: ivoirejobs-api
          imagePullPolicy: Always
          image: popokola/ivoirejobs-api
          ports:
            - containerPort: 80
          env:
            - name: SERVER_NAME
              value: :80

---
apiVersion: v1
kind: Service
metadata:
  name: ivoirejobs-api-service
spec:
  selector:
    app: ivoirejobs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ivoirejobs-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.barassage.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ivoirejobs-api-service
                port:
                  number: 80
        

