name: Build Flutter Android App

on:
  push:
    paths:
      - 'front_app/**'  # Trigger this workflow only on changes to the front_app directory
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build_flutter_android:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Generate .env File for Flutter
        run: |
          echo "MAPBOX_API_URL=${{ secrets.MAPBOX_API_URL }}" >> ./front_app/.env
          echo "MAPBOX_SEARCH_URL=${{ secrets.MAPBOX_SEARCH_URL }}" >> ./front_app/.env
          echo "MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}" >> ./front_app/.env

      - run: flutter pub get
        working-directory: ./front_app

      - run: flutter build apk --release
        working-directory: ./front_app

      - run: flutter build appbundle
        working-directory: ./front_app

      - name: Zip the APK
        run: |
          cd ./front_app/build/app/outputs/flutter-apk
          zip -r release-apk.zip app-release.apk

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Get the latest release tag
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(gh release list --limit 1 | awk '{print $1}')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          if [ -z "$LATEST_RELEASE" ]; then
            NEW_VERSION="v0.0.1"
          else
            NEW_VERSION=$(echo $LATEST_RELEASE | awk -F. -v OFS=. '{if($3+1 == 100){$2+=1;$3=0}else{$3+=1}}1')
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ env.NEW_VERSION }}
        run: |
          gh release create "$NEW_VERSION" ./front_app/build/app/outputs/flutter-apk/release-apk.zip --title "Release $NEW_VERSION" --notes "Release version $NEW_VERSION"
